---
title: "Exploration of variance in low-probability binomial events"
author: "Abhraneel Sarma"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggdist)
```

## Low probability binomial events
By this, I am referring to a binomial random variable with small values of p (i.e. close to zero)

```{r}
m = 2^c(1:12)
trials = 50 #c(10, 20, 30, 40, 50, 100)
prob = c(0.05, 0.1, 0.2, 0.3, 0.4, 0.5)
n = 100

set.seed(100)

simulations = crossing(m, trials, prob, n = 1:n) %>%
  mutate(
    event = pmap(list(m, trials, prob), ~ rbinom(..2, ..1, ..3)),
    score = map_dbl(event, mean)/m,
    trials = factor(trials)
  )

simulations
```


```{r, fig.height = 6, fig.width = 10}
simulations %>%
  group_by(m, trials, prob) %>%
  summarise(score = list(score), .groups = "drop") %>%
  median_qi(score) %>%
  ggplot() +
  geom_pointinterval(aes(x = m, y = score, ymin = .lower, ymax = .upper), position = "dodge") +
  geom_hline(aes(yintercept = prob)) +
  geom_hline(aes(yintercept = 0), size = 0.1, colour = "#efefef") +
  geom_hline(aes(yintercept = 2*prob), size = 0.1, colour = "#efefef") +
  scale_x_log10() +
  scale_color_brewer(palette = "OrRd") +
  facet_wrap( ~ prob, scales = "free") +
  theme_minimal()
```


```{r, fig.height = 6, fig.width = 10}
simulations %>%
  mutate(n = factor(n)) %>%
  ggplot(aes(y = score, x = m, group = n)) +
  # geom_point() +
  geom_line(alpha = 0.1) +
  geom_hline(aes(yintercept = prob)) +
  geom_hline(aes(yintercept = 0), size = 0.1, colour = "#efefef") +
  geom_hline(aes(yintercept = 2*prob), size = 0.1, colour = "#efefef") +
  # ylim(c(0, 0.5)) +
  scale_x_log10() +
  scale_color_brewer(palette = "OrRd") +
  facet_wrap( ~ prob, scales = "free") +
  theme_minimal()
```



