---
title: "B-H incentives"
output: html_document
---


```{r setup, warning = FALSE, message = FALSE}
library(ggplot2)
library(dplyr)
library(tidybayes)
library(purrr)
library(tidyr)
library(gganimate)
library(ggrepel)
library(modelr)
library(glue)
```

Overview: Using B-H in justifying the FP penalty = 19

## Setup params

```{r}
alpha <- 0.05
K <- 20
mu <- 1.5
sigma <- 2.5     # ACHTUNG: mu/sd is c(1.2/3, 1.5/2.5, 1.6/2) in stimuli
p_null <- 0.5
n_iter <- 3000   # number of iterations in simulation
```

## p-value PDF, CDF, invCDF defs

```{r}
f_p <- function(x, mu, sigma, K) {
  dnorm(qnorm(1 - x) - sqrt(K) * mu / sigma) / dnorm(qnorm(1 - x))
}

F_p <- function(x, mu, sigma, K) {
  1 - pnorm(qnorm(1 - x) - sqrt(K) * mu / sigma)
}


# inverse CDF of p-value
F_p_inv <- function(q, mu, sigma, K, l = 0, u = 1){
  uniroot(function(p) F_p(p, mu, sigma, K) - q, lower = l, upper = u)$root
}

# random sample from PDF of p-value using its invCDF
rfp <- function( mu, sigma){
  q <- runif(1)
  F_p_inv(q, mu, sigma, K)
}
```


## Sampling p-values


```{r}
(df <- expand.grid(
  nregions = c(8, 12),
  iter = 1:n_iter
) %>%
  uncount(nregions, .remove = FALSE, .id = "panel") %>%
  group_by(iter, nregions) %>%
  mutate(
    mu = rbinom(nregions, 1, 1 - p_null), 
    p = map_dbl(mu, ~rfp(.x, sigma)), 
    p_bh = p.adjust(p, method = "BH"),
    reject = p_bh < alpha
  )  %>%
  summarize(k = sum(reject)) 
)



df %>%
  ggplot(aes(x = factor(k))) +
  geom_bar() + 
  facet_grid(. ~ nregions)
```
## Expected value of number of selections

```{r}
(expected_nselect <-
   df %>%
  group_by(nregions) %>%
  count(k) %>% 
  mutate(dens = k / sum(k),
         E_nselectk = k * dens) %>%
  summarize(E_nselect = sum(E_nselectk), .groups = "drop")
)
```

## FP penalty from utility inequality

```{r}
expected_nselect %>%
  mutate(a = (nregions - 2 * nregions * p_null + nregions * E_nselect * p_null)/(E_nselect * p_null))

```

## Alpha from maximizing payout

Given P(null), FP penalty = 19, etc., what's the $\alpha$ that maximizes the expected payout unter 

```{r}
(expected_payout <- expected_nselect %>%
  mutate(E_tp = E_nselect * (1 - p_null),
         E_tn = (nregions - E_nselect) * p_null,
         E_fp = E_nselect * p_null,
         E_fn = (nregions - E_nselect) * (1 - p_null),
         E_payout = E_tp - 19 * E_fp + E_tn - E_fn)
)
```



## Grid search for the good alpha

### Encapsulate simulation function


```{r}
finding_payout <- function(alpha_thres){
  df <- expand.grid(
    nregions = c(8, 12),
    iter = 1:n_iter
  ) %>%
    uncount(nregions, .remove = FALSE, .id = "panel") %>%
    group_by(iter, nregions) %>%
    mutate(
      mu = rbinom(nregions, 1, 1 - p_null), 
      p = map_dbl(mu, ~rfp(.x, sigma)), 
      p_bh = p.adjust(p, method = "BH"),
      reject = p_bh < alpha_thres
    )  %>%
    summarize(k = sum(reject), .groups = "drop") 
  
  expected_nselect <-
    df %>%
    group_by(nregions) %>%
    count(k) %>% 
    mutate(dens = k / sum(k),
           E_nselectk = k * dens) %>%
    summarize(E_nselect = sum(E_nselectk), .groups = "drop")
  
  expected_payout <- expected_nselect %>%
    mutate(E_tp = E_nselect * (1 - p_null),
           E_tn = (nregions - E_nselect) * p_null,
           E_fp = E_nselect * p_null,
           E_fn = (nregions - E_nselect) * (1 - p_null),
           E_payout = E_tp - 19 * E_fp + E_tn - E_fn)
  
  expected_payout
}

```


```{r}
sim_df <- seq(from = 0.05, to = 0.5, by = 0.01) %>%
  set_names() %>%
  map_df(~finding_payout(.), .id = "alpha") 
 


sim_df %>% 
  ggplot(aes(as.numeric(alpha), E_payout)) + 
  geom_point() + 
  facet_grid(. ~ nregions)


  
```



